Repository nanoframework/nf-Community-Targets, pull requests merged in 2021-12, with the labels that each got.

#189 Simplification of WP HAL Interface
  ChibiOS/BrainPad2/common/usbcfg.h
  ChibiOS/BrainPad2/nanoBooter/main.c
  ChibiOS/BrainPad2/nanoCLR/main.c
  ChibiOS/GHI_FEZ_CERB40_NF/common/usbcfg.h
  ChibiOS/GHI_FEZ_CERB40_NF/nanoBooter/main.c
  ChibiOS/GHI_FEZ_CERB40_NF/nanoCLR/main.c
  ChibiOS/I2M_ELECTRON_NF/common/usbcfg.h
  ChibiOS/I2M_ELECTRON_NF/nanoBooter/main.c
  ChibiOS/I2M_ELECTRON_NF/nanoCLR/main.c
  ChibiOS/I2M_OXYGEN_NF/common/usbcfg.h
  ChibiOS/I2M_OXYGEN_NF/nanoBooter/main.c
  ChibiOS/I2M_OXYGEN_NF/nanoCLR/main.c
  ChibiOS/MBN_QUAIL/common/usbcfg.h
  ChibiOS/MBN_QUAIL/nanoBooter/main.c
  ChibiOS/MBN_QUAIL/nanoCLR/main.c
  ChibiOS/PybStick2x/common/usbcfg.h
  ChibiOS/PybStick2x/nanoBooter/main.c
  ChibiOS/PybStick2x/nanoCLR/main.c
  ChibiOS/ST_NUCLEO144_F412ZG_NF/common/usbcfg.h
  ChibiOS/ST_NUCLEO144_F412ZG_NF/nanoBooter/main.c
  ChibiOS/ST_NUCLEO144_F412ZG_NF/nanoCLR/main.c
  ChibiOS/ST_STM32F4_DISCOVERY/common/usbcfg.h
  ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/main.c
  ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/main.c
  ChibiOS/WEACT_F411CE/common/usbcfg.h
  ChibiOS/WEACT_F411CE/nanoBooter/main.c
  ChibiOS/WEACT_F411CE/nanoCLR/main.c
Labels: Type: enhancement

#193 Fix brainpad2 missing from CI build
  ChibiOS/BrainPad2/board.c
  ChibiOS/BrainPad2/board.h
  ChibiOS/BrainPad2/cmake-variants.json
  ChibiOS/BrainPad2/nanoBooter/halconf.h
  ChibiOS/BrainPad2/nanoBooter/mcuconf.h
  ChibiOS/BrainPad2/nanoCLR/halconf.h
  ChibiOS/BrainPad2/nanoCLR/mcuconf.h
  azure-pipelines.yml
Labels: Area: Config-and-Build

#186 Update ChibiOS HAL to 21.11
  ChibiOS/BrainPad2/nanoBooter/halconf.h
  ChibiOS/BrainPad2/nanoCLR/halconf.h
  ChibiOS/GHI_FEZ_CERB40_NF/nanoBooter/halconf.h
  ChibiOS/GHI_FEZ_CERB40_NF/nanoCLR/halconf.h
  ChibiOS/I2M_ELECTRON_NF/nanoBooter/halconf.h
  ChibiOS/I2M_ELECTRON_NF/nanoCLR/halconf.h
  ChibiOS/I2M_OXYGEN_NF/nanoBooter/halconf.h
  ChibiOS/I2M_OXYGEN_NF/nanoCLR/halconf.h
  ChibiOS/MBN_QUAIL/nanoBooter/halconf.h
  ChibiOS/MBN_QUAIL/nanoCLR/halconf.h
  ChibiOS/NETDUINO3_WIFI/nanoBooter/halconf.h
  ChibiOS/NETDUINO3_WIFI/nanoCLR/halconf.h
  ChibiOS/PybStick2x/nanoBooter/halconf.h
  ChibiOS/PybStick2x/nanoCLR/halconf.h
  ChibiOS/ST_NUCLEO144_F412ZG_NF/nanoBooter/halconf.h
  ChibiOS/ST_NUCLEO144_F412ZG_NF/nanoCLR/halconf.h
  ChibiOS/ST_NUCLEO144_F439ZI/nanoBooter/halconf.h
  ChibiOS/ST_NUCLEO144_F439ZI/nanoCLR/halconf.h
  ChibiOS/ST_NUCLEO144_F746ZG/nanoBooter/halconf.h
  ChibiOS/ST_NUCLEO144_F746ZG/nanoCLR/halconf.h
  ChibiOS/ST_NUCLEO64_F401RE_NF/nanoBooter/halconf.h
  ChibiOS/ST_NUCLEO64_F401RE_NF/nanoCLR/halconf.h
  ChibiOS/ST_NUCLEO64_F411RE_NF/nanoBooter/halconf.h
  ChibiOS/ST_NUCLEO64_F411RE_NF/nanoCLR/halconf.h
  ChibiOS/ST_STM32F411_DISCOVERY/nanoBooter/halconf.h
  ChibiOS/ST_STM32F411_DISCOVERY/nanoCLR/halconf.h
  ChibiOS/ST_STM32F4_DISCOVERY/nanoBooter/halconf.h
  ChibiOS/ST_STM32F4_DISCOVERY/nanoCLR/halconf.h
  ChibiOS/WEACT_F411CE/nanoBooter/halconf.h
  ChibiOS/WEACT_F411CE/nanoCLR/halconf.h
Labels: Type: dependencies

#197 Fix cmake variants template for ST_NUCLEO144_F746ZG
  ChibiOS/ST_NUCLEO144_F746ZG/cmake-variants.json
Labels: Area: Config-and-Build

#198 Update to IDF 4.3.2
  azure-pipelines.yml
Labels: Type: dependencies
